clusterName: unicorn
enableConfigSyncer: true
eventForwarder:
  receivers:
  - notifier: Mailgun
    to:
    - ops@example.com
  rules:
  - namespaces:
    - kube-system
    operations:
    - CREATE
    resources:
    - group: ""
      resources:
      - events
  - operations:
    - CREATE
    resources:
    - group: ""
      resources:
      - nodes
      - persistentvolumes
      - persistentvolumeclaims
  - operations:
    - CREATE
    resources:
    - group: storage.k8s.io
      resources:
      - storageclasses
  - operations:
    - CREATE
    resources:
    - group: extensions
      resources:
      - ingresses
  - operations:
    - CREATE
    resources:
    - group: voyager.appscode.com
      resources:
      - ingresses
  - operations:
    - CREATE
    resources:
    - group: certificates.k8s.io
      resources:
      - certificatesigningrequests
notifierSecretName: notifier-config
recycleBin:
  handleUpdates: false
  path: /tmp/kubed/trash
  ttl: 168h0m0s
