apiVersion: v1
data:
  config.yaml: ZW5hYmxlQ29uZmlnU3luY2VyOiB0cnVlCmV2ZW50Rm9yd2FyZGVyOgogIGV2ZW50TmFtZXNwYWNlczoKICAtIGt1YmUtc3lzdGVtCiAgZm9yd2FyZFdhcm5pbmdFdmVudHM6IHRydWUKICBub3RpZnlPbkluZ3Jlc3NBZGQ6IHRydWUKICBub3RpZnlPblN0b3JhZ2VBZGQ6IHRydWUKICByZWNlaXZlcjoKICAgIG5vdGlmaWVyOiBtYWlsZ3VuCiAgICB0bzoKICAgIC0gb3BzQGV4YW1wbGUuY29tCmphbml0b3JzOiB7fQpub3RpZmllclNlY3JldE5hbWU6IGt1YmVkLW5vdGlmaWVyCnJlY3ljbGVCaW46CiAgaGFuZGxlX3VwZGF0ZTogdHJ1ZQogIHBhdGg6IC90bXAva3ViZWQKICByZWNlaXZlcjoKICAgIG5vdGlmaWVyOiBtYWlsZ3VuCiAgICB0bzoKICAgIC0gb3BzQGV4YW1wbGUuY29tCiAgdHRsOiAxNjhoMG0wcwpzbmFwc2hvdHRlcjoKICBTdG9yYWdlOgogICAgZ2NzOgogICAgICBidWNrZXQ6IHJlc3RpYwogICAgICBwcmVmaXg6IG1pbmlrdWJlCiAgICBzdG9yYWdlU2VjcmV0TmFtZTogc25hcC1zZWNyZXQKICBzYW5pdGl6ZTogdHJ1ZQogIHNjaGVkdWxlOiAnQGV2ZXJ5IDZoJwo=
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    app: kubed
  name: kubed-config
  namespace: kube-system
