apiVersion: v1
data:
  config.yaml: ZXZlbnRGb3J3YXJkZXI6CiAgZXZlbnROYW1lc3BhY2VzOgogIC0ga3ViZS1zeXN0ZW0KICBmb3J3YXJkV2FybmluZ0V2ZW50czogdHJ1ZQogIG5vdGlmeU9uSW5ncmVzc0FkZDogdHJ1ZQogIG5vdGlmeU9uU3RvcmFnZUFkZDogdHJ1ZQogIHJlY2VpdmVyOgogICAgbm90aWZpZXI6IG1haWxndW4KICAgIHRvOgogICAgLSBvcHNAZXhhbXBsZS5jb20KamFuaXRvcnM6IHt9Cm5vdGlmaWVyU2VjcmV0TmFtZToga3ViZWQtbm90aWZpZXIKcmVjeWNsZUJpbjoKICBoYW5kbGVfdXBkYXRlOiB0cnVlCiAgcGF0aDogL3RtcC9rdWJlZAogIHJlY2VpdmVyOgogICAgbm90aWZpZXI6IG1haWxndW4KICAgIHRvOgogICAgLSBvcHNAZXhhbXBsZS5jb20KICB0dGw6IDE2OGgwbTBzCnNuYXBzaG90dGVyOgogIFN0b3JhZ2U6CiAgICBnY3M6CiAgICAgIGJ1Y2tldDogcmVzdGljCiAgICAgIHByZWZpeDogbWluaWt1YmUKICAgIHN0b3JhZ2VTZWNyZXROYW1lOiBzbmFwLXNlY3JldAogIHNhbml0aXplOiB0cnVlCiAgc2NoZWR1bGU6ICdAZXZlcnkgNmgnCg==
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    app: kubed
  name: kubed-config
  namespace: kube-system
