apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubed
  namespace: kube-system
  labels:
    app: kubed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubed
  template:
    metadata:
      labels:
        app: kubed
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''        
    spec:
      containers:
      - name: kubed
        args:
        - run
        - --v=3
        image: appscode/kubed:0.1.0
        ports:
        - containerPort: 56790
          name: http
          protocol: TCP
        volumeMounts:
          - mountPath: /tmp
            name: scratchdir
      tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Exists"
      volumes:
        - emptyDir: {}
          name: scratchdir
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubed
  name: kubed
  namespace: kube-system
spec:
  ports:
  - name: http
    port: 56790
    targetPort: http
  selector:
    app: kubed
