apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kubed-operator
  namespace: $KUBED_NAMESPACE
  labels:
    app: kubed
  initializers:
    pending: []
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubed
  template:
    metadata:
      labels:
        app: kubed
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      serviceAccountName: $KUBED_SERVICE_ACCOUNT
      imagePullSecrets: [$KUBED_IMAGE_PULL_SECRET]
      containers:
      - name: operator
        image: $KUBED_DOCKER_REGISTRY/kubed:0.5.0
        imagePullPolicy: IfNotPresent
        args:
        - run
        - --v=3
        - --api.address=:8080
        - --web.address=:56790
        ports:
        - containerPort: 8080
          name: api
          protocol: TCP
        - containerPort: 56790
          name: web
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /srv/kubed
        - name: scratch
          mountPath: /tmp
      volumes:
      - name: config
        secret:
          secretName: kubed-config
      - name: scratch
        emptyDir: {}
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
---
apiVersion: v1
kind: Service
metadata:
  name: kubed-operator
  namespace: $KUBED_NAMESPACE
  labels:
    app: kubed
spec:
  ports:
  - name: api
    port: 8080
    targetPort: api
  - name: web
    port: 56790
    targetPort: web
  selector:
    app: kubed
