apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: kubed-operator
  labels:
    app: kubed
rules:
- apiGroups:
  - voyager.appscode.com
  resources: ["*"]
  verbs: ["list", "watch"]
- apiGroups:
  - monitoring.appscode.com
  resources: ["*"]
  verbs: ["list", "watch"]
- apiGroups:
  - stash.appscode.com
  resources: ["*"]
  verbs: ["list", "watch"]
- apiGroups:
  - kubedb.com
  resources: ["*"]
  verbs: ["list", "watch"]
- apiGroups:
  - monitoring.coreos.com
  resources: ["*"]
  verbs: ["list", "watch"]
- apiGroups:
  - extensions
  resources: ["*"]
  verbs: ["list", "watch"]
- apiGroups:
  - apps
  resources: ["*"]
  verbs: ["list", "watch"]
- apiGroups: [""]
  resources: ["*"]
  verbs: ["list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  - secrets
  verbs: ["get", "create", "update"]
- apiGroups: ["autoscaling"]
  resources: ["*"]
  verbs: ["list", "watch"]
- apiGroups: ["batch"]
  resources: ["*"]
  verbs: ["list", "watch"]
- apiGroups: ["authorization.k8s.io"]
  resources: ["*"]
  verbs: ["list", "watch"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["*"]
  verbs: ["list", "watch"]
- apiGroups: ["abac.authorization.k8s.io"]
  resources: ["*"]
  verbs: ["list", "watch"]
- apiGroups: ["authentication.k8s.io"]
  resources: ["*"]
  verbs: ["list", "watch"]
- apiGroups: ["storage.k8s.io"]
  resources: ["*"]
  verbs: ["list", "watch"]
- apiGroups: ["certificates.k8s.io"]
  resources: ["*"]
  verbs: ["list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kubed-operator
  labels:
    app: kubed
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubed-operator
subjects:
- kind: ServiceAccount
  name: $KUBED_SERVICE_ACCOUNT
  namespace: $KUBED_NAMESPACE
---
# to read the config for terminating authentication
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: kubed-apiserver-extension-server-authentication-reader
  namespace: kube-system
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: $STASH_SERVICE_ACCOUNT
  namespace: $STASH_NAMESPACE
---
# to delegate authentication and authorization
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kubed-apiserver-auth-delegator
  labels:
    app: kubed
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: $STASH_SERVICE_ACCOUNT
  namespace: $STASH_NAMESPACE
---
# to let aggregated apiservers create admission reviews
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: appscode:kubed:apiserver-requester
  labels:
    app: kubed
rules:
- apiGroups: ['kubed.appscode.com']
  resources: ['*']
  verbs: ['get']
