eventForwarder:
  nodeAdded:
    forwardEvent: true
  storageAdded:
    forwardEvent: true
  ingressAdded:
    forwardEvent: true
  warningEvents:
    forwardEvent: true
    namespaces:
    - kube-system
  receiver:
    notifier: mailgun
    to:
    - ops@example.com
notifierSecretName: kubed-notifier
