apiVersion: v1
data:
  config.yaml: YXBpU2VydmVyOgogIGFkZHJlc3M6IDo4MDgxCiAgZW5hYmxlUmV2ZXJzZUluZGV4OiB0cnVlCiAgZW5hYmxlU2VhcmNoSW5kZXg6IHRydWUK
kind: Secret
metadata:
  creationTimestamp: 2017-07-27T10:07:49Z
  name: kubed-config
  namespace: kube-system
  resourceVersion: "27771685"
  selfLink: /api/v1/namespaces/kube-system/secrets/kubed-config
  uid: 71d5f538-72b3-11e7-8b69-12f236046fba
type: Opaque
