{{ if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "kubed.fullname" . }}
  labels:
    {{- include "kubed.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources:
  - configmaps
  - secrets
  verbs: ["get", "create", "patch", "delete"]
- apiGroups:
    - ""
  resources:
    - namespaces
  verbs: ["get"]
{{ end }}
