{{ define "kubed.config" }}
clusterName: "{{ .Values.config.clusterName }}"
enableConfigSyncer: {{ .Values.config.enableConfigSyncer }}
{{- if .Values.config.configSourceNamespace }}
configSourceNamespace: {{ .Values.config.configSourceNamespace }}
{{- end }}
{{- if .Values.config.include }}
{{ .Values.config.include | toYaml }}
{{- end }}
{{ end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kubed.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubed.labels" . | nindent 4 }}
data:
  config.yaml: {{ (include "kubed.config" .) | trim | b64enc | quote }}
