apiVersion: v1
kind: ConfigMap
metadata:
  name: kubed-config
  namespace: kube-system
  labels:
    app: kubed
data:
  config.yaml: |
    snapshotter:
      Storage:
        azure:
          container: bucket-for-snapshot
          prefix: minikube
        storageSecretName: azure-secret
      sanitize: true
      schedule: '@every 6h'
